---
- name: Set up control node
  hosts: local
  
  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../configuration/configuration.yml"
  
  vars:
    ansible_user: "{{ local_non_root_user }}"
    ansible_become: yes
    ansible_become_password: "{{ local_non_root_user_password }}"

  roles:
    - role: generate-ssh-keys
    - role: install-sshpass
    - role: install-wireguard
    - role: install-packer
    - role: install-terraform
    - role: install-yq
    - role: install-consul
    - role: install-lxd
    - role: set-up-veth0
    - role: set-up-consul-server
    - role: set-up-iptables
    - role: set-up-lxd
    - role: set-up-ca
    - role: set-up-lxd-certs
