---
- name: Set up control node
  hosts: local
  
  vars_files:
    - "{{ playbook_dir }}/../configuration/config_path.yml"
    - "{{ configuration_path }}"
  
  vars:
    ansible_user: "{{ local_non_root_user }}"
    ansible_become: yes
    ansible_become_password: "{{ local_non_root_user_password }}"
    #
    # Control node configuration switches - do not change unless you know what you are doing
    generate_ssh_keys: true
    install_wireguard: true
    set_up_wireguard: true
    install_lxd: true
    install_packer: true
    install_terraform: true

  roles:
    - role: generate-ssh-keys
    - role: install-sshpass
    - role: install-wireguard
    - role: set-up-wireguard
    - role: install-and-set-up-lxd
    - role: install-packer
    - role: install-terraform
