---
- name: Generate wireguard host private key
  shell: "wg genkey"
  register: generated_host_private_key
  when: set_up_wireguard


- name: Generate wireguard host public key
  shell:
    cmd: "wg pubkey"
    stdin: "{{ generated_host_private_key.stdout }}"
    stdin_add_newline: no
  register: generated_host_public_key
  when: set_up_wireguard


- name: Generate wireguard local private key
  shell: "wg genkey"
  register: generated_local_private_key
  when: set_up_wireguard


- name: Generate wireguard local public key
  shell:
    cmd: "wg pubkey"
    stdin: "{{ generated_local_private_key.stdout }}"
    stdin_add_newline: no
  register: generated_local_public_key
  when: set_up_wireguard


- name: Generate wireguard preshared key
  command: "wg genpsk"
  register: generated_preshared_key
  when: set_up_wireguard


- name: Create host wireguard configuration file
  template:
    mode: 644
    owner: root
    group: root
    dest: "/home/{{ local_non_root_user }}/ryo-host.conf"
    src: ryo-host.conf.j2
    force: yes
  when: set_up_wireguard


- name: Create local wireguard configuration file
  template:
    mode: 640
    owner: root
    group: root
    dest: /etc/wireguard/ryo-local.conf
    src: ryo-local.conf.j2
    force: yes
  when: set_up_wireguard


- name: Enable wireguard interface ryo-local as service
  service:
    name: wg-quick@ryo-local
    enabled: yes
    state: restarted
  when: set_up_wireguard
