---
- name: Make sure LXD apt packages are uninstalled and purged
  apt:
    name:
      - lxd
      - lxd-client
      - liblxc1
      - lxcfs
    update_cache: no
    purge: yes
    state: absent
  when: install_lxd

- name: Make sure ZFS Utils are installed
  apt:
    name: zfsutils-linux
    update_cache: yes
    state: present
  when: install_lxd


- name: Make sure snapd is installed
  apt:
    name: snapd
    update_cache: yes
    state: present
  when: install_lxd


- name: Make sure LXD snap package is installed
  snap:
    name: lxd
    channel: 4.0/stable
    state: present
  when: install_lxd


- name: Add non-root user to the lxd group
  user:
    name: "{{ local_non_root_user }}"
    groups:
     - lxd
    append: yes
    state: present
  when: install_lxd


# - name: Generate a random string as LXD core trust password
#   shell: "tr -dc A-Za-z0-9 </dev/urandom | head -c 12"
#   register: lxd_core_trust_password


# Write the LXD core trust password to a file to a file in the configuration directory (for use by later scripts)
#
# - name: Write the LXD core trust password to a file in the configuration directory
#   template:
#     mode: 0640
#     owner: "{{ local_non_root_user }}"
#     group: "{{ local_non_root_user }}"
#     dest: "{{ playbook_dir }}/../configuration/lxd_core_trust_password.yml"
#     src: lxd_core_trust_password.yml.j2
#     force: yes
#     backup: yes
#   when: install_lxd


- name: Wite the LXD preseed file to a file in the configuration directory
  template:
    mode: 0640
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    dest: "{{ playbook_dir }}/../configuration/preseed.yml"
    src: preseed.yml.j2
    force: yes
    backup: yes
  register: lxd_preseed_changes_made
  when: install_lxd


- name: Initialise LXD with preseed file
  shell:
    cmd: "lxd init --preseed < {{ playbook_dir }}/../configuration/preseed.yml"
  when:
    - lxd_preseed_changes_made is changed
    - install_lxd


- name: Add ubuntu-minimal LXD remote
  shell:
    cmd: 'lxc remote add --protocol="simplestreams" ubuntu-minimal https://cloud-images.ubuntu.com/minimal/releases/'
  become: yes
  become_user: "{{ local_non_root_user }}"
  when: install_lxd
