---
- name: Add non-root user to the lxd group
  user:
    name: "{{ local_non_root_user }}"
    groups:
     - lxd
    append: yes
    state: present

- name: Write the LXD preseed file to a file in the configuration directory
  template:
    mode: 0640
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    dest: "{{ playbook_dir }}/../configuration/preseed.yml"
    src: preseed.yml.j2
    force: yes
    backup: yes
  register: lxd_preseed_changes_made

- name: Initialise LXD with preseed file
  shell:
    cmd: "lxd init --preseed < {{ playbook_dir }}/../configuration/preseed.yml"
  when:
    - lxd_preseed_changes_made is changed

- name: Run lxc list to generate client certs and config directories
  shell:
    cmd: 'lxc list'
  become: yes
  become_user: "{{ local_non_root_user }}"

- name: Add ubuntu-minimal remote configuration to control node LXD remotes config file
  blockinfile:
    path: "/home/{{ local_non_root_user }}/snap/lxd/current/.config/lxc/config.yml"
    insertafter: "^remotes:"
    block: |2
        ubuntu-minimal:
          addr: https://cloud-images.ubuntu.com/minimal/releases
          protocol: simplestreams
          public: true
    marker: "  # {mark} ANSIBLE MANAGED BLOCK for ubuntu-minimal"
