---

# Create a directory for certificate authority files
- name: Create a directory for certificate authority files
  file:
    mode: 0700
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    path: "{{ playbook_dir }}/../configuration/ca"
    state: directory


# Generate a certificate authority private key
- name: Generate a certificate authority private key
  openssl_privatekey:
    owner: root
    group: root
    path: "{{ playbook_dir }}/../configuration/ca/ca.key"
    state: present
  register: ca_privatekey


# Generate a certificate authority CSR
- name: Generate a certificate authority CSR
  openssl_csr:
    owner: root
    group: root
    path: "{{ playbook_dir }}/../configuration/ca/ca.csr"
    privatekey_path: "{{ ca_privatekey.filename }}"
    common_name: "Control Node Root CA"
    use_common_name_for_san: false
    organization_name: "rollyourown.xyz Control Node CA"
    organizational_unit_name: "Control Node CA"
    basic_constraints:
      - CA:TRUE
      - pthlen:0
    basic_constraints_critical: yes
    key_usage:
      - keyCertSign
      - cRLSign
      - digitalSignature
    key_usage_critical: yes
    state: present
  register: ca_csr


# Generate a self-signed CA certificate
- name: Generate a self-signed CA certificate
  openssl_certificate:
    owner: root
    group: root
    path: "{{ playbook_dir }}/../configuration/ca/ca.crt"
    csr_path: "{{ ca_csr.filename }}"
    privatekey_path: "{{ ca_privatekey.filename }}"
    provider: selfsigned
    selfsigned_create_subject_key_identifier: always_create
    selfsigned_not_after: "+36500d"
    state: present
