---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later


# Copy iptables rules script (making executable)
#
- name: Copy iptables rules rules script
  template:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/iptables-rules.sh
    src: iptables-rules.sh.j2
    force: yes


# Copy iptables rules service definition
#
- name: Copy iptables rules service definition
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /lib/systemd/system/iptables-rules.service
    src: iptables-rules.service
    force: yes


# Enable iptables rules service
#
- name: Enable iptables rules service
  service:
    name: iptables-rules.service
    enabled: yes
    state: started
