# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

## If this file is placed in a different location to the directory `configuration` in 
# the cloned repository, then config_path.yml **must** be updated with the new path to the file

## WARNING: After adding configuration, never push this file, with secrets, 
# to a repository nor publish in any other way!


#-----------------------
# REQUIRED Configuration
#-----------------------

# Copy this file to `configuration.yml` in the same directory and add
# your own configuration parameters

# Local user configuration
#-------------------------

# Enter your non-root username for this machine
# (note: the user must be a member of the sudo group
# - `useradd <username> sudo` if not already a sudo user)
local_non_root_user: <USER_NAME>

# SECRET: Enter your non-root user password for this machine. Enter "" if
# no password is required (e.g. with a Multipass VM)
local_non_root_user_password: <PASSWORD>


#-------------------------------------------------------------------
# DEFAULT configuration - change only if you know what you are doing
#-------------------------------------------------------------------

# Only change the veth0 interface network part if needed to avoice overlapping 
# with IP address ranges in the control node local network
veth0_network_part: "10.100.100"
veth0_network_ipv6_prefix: "fd10:10:100:100"

# Leave as default if SSH keys are generated by local-setup.sh script, 
# otherwise enter the paths to the non-root user's SSH private and public keys here
local_non_root_user_ssh_private_key_file_path: "/home/{{ local_non_root_user }}/.ssh/ryo_id_ssh_rsa" 
local_non_root_user_ssh_public_key_file_path: "/home/{{ local_non_root_user }}/.ssh/ryo_id_ssh_rsa.pub"

# Change to 'true' if 2FA should be used for non-root user login via public 
# SSH port and enter the path to the non-root user's google authenticator 
# configuration file
local_non_root_use_google_authenticator: false
local_non_root_user_google_authenticator_file: <PATH>
