---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Make sure yq apt packages are uninstalled and purged
  apt:
    name: yq
    update_cache: no
    purge: yes
    state: absent

- name: Make sure snapd is installed
  apt:
    name: snapd
    update_cache: yes
    state: present

- name: Make sure yq snap package is installed
  snap:
    name: yq
    state: present
